image: node:0.12.7-wheezy

stages:
  - buildpage
  - testpage

build:
  stage: buildpage
  script:
    - npm install -g bower gulp
    - npm install
    - bower --allow-root install
    - gulp
  only:
    - master

test:
  stage: testpage
  script:
    - echo "deb http://http.debian.net/debian wheezy-backports main" >> /etc/apt/sources.list
    - apt-get update
    - apt-get -t wheezy-backports install -y nginx
    - npm run test-page
    - cp nginx.sample.conf nginx.conf
    - sed -i "s#0ROOT0#$(pwd)#g" nginx.conf
    - nginx -g 'pid /dev/nginx.pid;' -c $(pwd)/nginx.conf
    - cp test/longpage.md dest/pages/longpage.md
    - npm link mocha
    - mocha
    - nginx -g 'pid /tmp/nginx.pid;' -s stop
  only:
    - master
